### ISSUE TITLE
Stable version for CMIP6?

### ISSUE THREAD

**Issue by pabretonniere** [EC-Earth/ece2cmor3#135]
Hi @treerink 

We want to start testing ece2cmor for the upcoming CMIP6 experiments. As there is no tag, which version/commit/branch do you recommend us to use?
Also, do you have a pptd associated with the cmorization?

Thanks,

Pierre-Antoine

@etiennesky

**Comment by treerink** [comment]
The latest checkout of the master

**Comment by etiennesky** [comment]
Hi @treerink it would be nice to have a tag to use once things are stable.

About the pptd question, I assume you use the standard ppt and nemo xml files from trunk?

@pabretonniere look at the requirements are CMOR3==3.3.1

**Comment by treerink** [comment]
Gijs will first finish the nocdo branch and merge it into the master. We expect with that a significant improvement in the performance of the cmorization, and it will circumvent the gribapi issues.

**Comment by treerink** [comment]
What do you mean with pptd?

You mean the dr2ppt tool?

**Comment by pabretonniere** [comment]
Thanks for the quick reply!
For the pptd, we wonder with which IFS files (therefore pptd) you are basing your developments of the cmorization.

**Comment by treerink** [comment]
I think for CMIP6 it is more the other way around: we are preparing the data request for EC-Earth, which is ongoing work, and after all requested variables are identified it will be possible to construct the IFS ppt files. In order to facilitate the creation of the ppt files for each MIP experiment we added the dr2ppt script (it needs to be checked in practice and might need some additional development) with which one just specifies the MIP, the experiment, the tier, and the priority of the variables (similar as for drq) and based on the EC-Earth available variables the ppt files will be created.

**Comment by treerink** [comment]
We aim for an 0.5 stable version before Lisbon.

**Comment by goord** [comment]
We are now working on ece2cmor3 v0.9 (see labels)

**Comment by treerink** [comment]
See tagged versions. Current tagged version 0.9: https://github.com/EC-Earth/ece2cmor3/releases/tag/0.9.0
And upcoming 0.95 and 1.0
