### ISSUE TITLE
Processing NEMO output fails

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#174]
I try processing NEMO output (daily and monthly) output from a historical experiment but get stuck right at the beginning:
````
INFO:ece2cmor3.ece2cmorlib:Selected 54 NEMO tasks from 54 input tasks
INFO:ece2cmor3.nemo2cmor:Creating NEMO grids in CMOR...
Traceback (most recent call last):
  File "/var/lib/slurm/slurmd/job18784129/slurm_script", line 97, in <module>
    main()
  File "/var/lib/slurm/slurmd/job18784129/slurm_script", line 91, in main
    ece2cmorlib.perform_nemo_tasks(args.datadir, args.exp, startdate, length)
  File "/home/sm_wyser/.conda/envs/ece2cmor3-3-2/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/ece2cmorlib.py", line 175, in perform_nemo_tasks
    if not nemo2cmor.initialize(datadir, expname, tableroot, startdate, interval):
  File "/home/sm_wyser/.conda/envs/ece2cmor3-3-2/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 53, in initialize
    create_grids()
  File "/home/sm_wyser/.conda/envs/ece2cmor3-3-2/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 291, in create_grids
    grid = read_grid(gridfiles[0])
  File "/home/sm_wyser/.conda/envs/ece2cmor3-3-2/lib/python2.7/site-packages/ece2cmor3-1.0.0-py2.7.egg/ece2cmor3/nemo2cmor.py", line 299, in read_grid
    lons = ds.variables['nav_lon'][:,:]
KeyError: 'nav_lon'
````
I used a fairly recent version of the EC-Earth model (r5498) which includes all the recent updates of NEMO, in partcular a lot of stuff from XIOS and SHACONEMO. Is it possible that some important variable or dimension names have changed in the NEMO output and these changes are not reflected yet in nemopar.json?

BTW: how do we ensure backward compatibility in ece2cmor3 with respect to changes in the NEMO output? Some people will still have to process Primavera (=old NEMO) output, while others already start processing CMIP6 (=new NEMO output) output.

**Comment by goord** [comment]
Hmm this means they have changed the grid naming in the NEMO nc files... Can you check which name is given to the lat and lon variables? I can make ece2cmor2 check for both variables. It's not nice, but it is backward compatible

**Comment by klauswyser** [comment]
The lat/lon variables are still called ``nav_lat`` and ``nav_lon``, but the dimension names now differ between different files:

grid_T:
````
dimensions:
        axis_nbounds = 2 ;
        x = 362 ;
        y = 292 ;
        deptht = 75 ;
        time_counter = UNLIMITED ; // (12 currently)
````

icemod:
````
dimensions:
        axis_nbounds = 2 ;
        x_grid_T = 362 ;
        y_grid_T = 292 ;
        x_grid_U = 362 ;
        y_grid_U = 292 ;
        x_grid_V = 362 ;
        y_grid_V = 292 ;
        ncatice = 5 ;
        time_counter = UNLIMITED ; // (12 currently)
````
Could this be the problem?

**Comment by etiennesky** [comment]
Hi @klauswyser I also found this problem on CCA, but not on MN4. Which platform did you use for this test?

**Comment by etiennesky** [comment]
Also @klauswyser this is causing hiresclim2 to fail see https://github.com/plesager/ece3-postproc/issues/29

**Comment by etiennesky** [comment]
maybe we should open a bug report on the portal? I think this should be fixed ASAP, because many post-processing tools are broken now (ece3post, ece2cmor3)

**Comment by klauswyser** [comment]
Sorry, my answer above to @goord was incorrect. It's not just dimension names that change but also the  names of the lon/lat variables. Here is from icemod:
````
        float nav_lat_grid_T(y_grid_T, x_grid_T) ;
        float nav_lon_grid_T(y_grid_T, x_grid_T) ;
        float nav_lat_grid_U(y_grid_U, x_grid_U) ;
        float nav_lon_grid_U(y_grid_U, x_grid_U) ;
        float nav_lat_grid_V(y_grid_V, x_grid_V) ;
        float nav_lon_grid_V(y_grid_V, x_grid_V) ;
````
Also my grid_W file now contains two different horizontal grids.

I am using the latest ``file_def.xml`` from the trunk which contains many Shaconemo updates (but is certainly not the one that should be used for DECK simulations, @pabretonniere is working on that). The icemod file will definitely contain multiple grids for CMIP6, not sure about the other NEMO output files. I see two possible ways to tackle this:
1. Update ece2cmor.py to handle mutiple grids from the same NEMO output file. This is somewhat tricky because we have to keep track of which variable uses which grid. But maybe this is already taken care of?
2. We can edit ``file_def.xml`` to make sure that only variables from one grid are in the same file. In that case xios doesn't add ``_grid_T`` etc to dimensions or coordinate variables. (This would automatically solve all our headaches with Barakuda, EMoP and hiresclim2.) The drawback is that  drq2ppt has to check that variables on different grids don't end up in the same output file, and we cannot fully rely on xml files from other sources (e.g. Shaconemo)
Any suggestions for how to tackle the problem?

**Comment by etiennesky** [comment]
Hi everyone. This is a complex issue with many possible side-effects, shouldn't we discuss this on the ec-earth portal?

**Comment by treerink** [comment]
Just to inform you: I have been working the last weeks full time on a way to combine the Shaconemo ping file identification of the cmor - nemo code relation and the nemo field_def files in order to create nemo file_def files based on the CMIP6 data request, i.e. in the end a drq2nemo_file_def tool will produce this file_def file(s). The nasty thing here is the diverse and flexible definition levels and the inheritance XIOS logics applied within the xml tree structure. Especially, to detect in all cases the grid definition of each variable. However, I think I am quite far at this moment and about to create files based on the triple selection: model component, output frequency and spatial grid. I used Shaconemo r253 for the field_def files but by changing the path it can use the ec-earth ones. The nemo cmorization will be tailored to this, in fact it will become simpler then.

As my script now allows many checks on the combined field_def files, I foresee enough points to discuss however.

**Comment by thomasarsouze** [comment]
I would agree with Etienne in the sense that is issue is affecting many components both in the run and post process, and is not only limited to ece2cmor, so maybe we should discuss that on the ec-earth portal.
My feeling on this is that we should definitely modify the xml files the way we want to instead of checking for either nav_lon or nav_lon_grid_[UVT] in all softs / scripts.
I would just emphasize that for the ocean dynamical variables, we are already separating the variables in function of their grid, so I guess the most coherent modification to do here would be do the same thing for the ice, i.e. name the files icemod_grid[UVT]. However, for backward compatibility with most tools / users scripts, it could also be safe to keep the icemod file and only add icemod_grid_[UV] files.

**Comment by goord** [comment]
@treerink Can you confirm the dimension name changes above are the final ones for CMIP6? Are we going to have multiple grids in a netcdf file?

**Comment by treerink** [comment]
In the current design the grouping is also per grid definition, so that means we don't have now multiple grids in one netcdf file. This is however a matter of taste it could easily be organized differently. But @goord as we discussed together the current choice fits most well with the current cmorization, and thus will the other option generate more work, while we could not really think of advantage other then that the amount of output files reduces.

I propose to close this issue, as testing of the nemo namelists goes on in issue 518 on the EC-Earth portal and of the cmorization of these results in #202. If someone disagrees please open again.

**Comment by aearamos** [comment]
Hi @treerink, I've been testing a piControl run with the nemo files generated from the drq. I was able to run the simulations and got the files divided by grid (2D, 3D, 1point), but when I ran the cmorization, it seemed like it couldn't read the files and it just skipped all the variables. Is cmorization working for the different names in the NEMO output?
