### ISSUE TITLE
revert develop-bsc-cmip6 branch merge into master

### ISSUE THREAD

**Issue by goord** [EC-Earth/ece2cmor3#271]
It seems that there has been an unintended merge from the bsc dev branch into the master, resulting in an incompatible nemopar.json with the new EC-Earth output and an issue with grib code 168 filtering (see https://github.com/EC-Earth/ece2cmor3/issues/230#issuecomment-428249850)

This may be the result of issuing a github pull request, I have had this problem myself too: to merge the master into your branch, just do
```
git pull
git checkout develop-bsc-cmip6
git pull
git merge master
git commit -am 'Merge master in develop-bsc-cmip6 branch.'
git push
```

**Comment by treerink** [comment]
A clean git revert of this unintended merge causes more work because of the corrections on top of them already (see https://github.com/EC-Earth/ece2cmor3/issues/230#issuecomment-428249850). Therefore I just freshly generated the `nemopar.json` and have commited that one in 037176b7d71a253e4ec77e41d6122e6acd242ddf and we leave the applied on-top-corrections as they are now.

**Comment by treerink** [comment]
Closing issue after the changes have been cancelled.
