### ISSUE TITLE
Some variables like sltovovrt are present in the file_def but not in the data request file

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#372]
Some variables like `sltovovrt` are present in the `file_def` file but not in the data request file. This has to be checked, this should not be possible.

Arthur can you list the other variables here?

**Comment by aearamos** [comment]
Hi Thomas, 
So far I noticed these variables that are in the file_def.xml files (in EC-EARTH-AOGCM/cmip6-experiment-CMIP-piControl), but not in the excel tables from the data request:

Omon table:
htovgyre
hfibthermds2d
htovovrt
sossq
tossq
sltovovrt
sltovgyre

SIday table:
sitimefrac
sisnthick
sitemptop
sispeed

 SImon - these variables are in the drq excel table for piControl 1 1, but not in the xml files. 
simpconc
sirdgconc
sisnconc

Since I only noticed this difference today, there might be some other variables missing or maybe some are already fixed and I didn't see it. I've been cmorising my runs with the Excel tables instead of the json files, so I noticed I got less cmorised variables than I was outputing in nemo. 

I did not check for any variables from ifs. 

Thank you again.

Arthur

**Comment by treerink** [comment]
If the correct 'joint' CMIP6 data request file is viewed one can find these variables. 

For instance the variable `sltovovrt` is asked in the `Omon` table in the file:
`````
ece2cmor3/scripts/cmip6-data-request/cmip6-data-request-m=CMIP.DCPP.LS3MIP.PAMIP.RFMIP.ScenarioMIP.VolMIP.CORDEX.DynVar.SIMIP.VIACSAB-e=piControl-t=1-p=1/cmvme_cm.co.dc.dy.ls.pa.rf.sc.si.vi.vo_piControl_1_1.xlsx
`````
Which is the file which has been created/used by `genecec` and which should be used to cmorize the piControl experiment for EC-Earth3-AOGCM.

See also [ec-earth step by step wiki](https://dev.ec-earth.org/projects/cmip6/wiki/Step-by-step_guide_for_making_CMIP6_experiments).

This shows that issue #253 is rather relevant, because for these joint data request it might be not so evident for everybody to select / create the correct CMIP6 data request for cmorization.

Closing this issue, as I think this on it self is clarified now.
