### ISSUE TITLE
Problem with cmor.zfactor in table 6hrLev

### ISSUE THREAD

**Issue by tommibergman** [EC-Earth/ece2cmor3#376]
Time1 and time indices of actual variable ec550aer and zfactor variable ps are in conflict. I made an issue on CMOR-table github:

[https://github.com/PCMDI/cmip6-cmor-tables/issues/230](url)

**Comment by ufladrich** [comment]
We have seen the same error while cmorising AMIP. (Hence, TM5 label could be removed)

**Comment by goord** [comment]
This is a fundamental problem with a dynamic vertical discretization: is the surface pressure that determines the layer thicknesses supposed to be averaged for averaged 3D fields? I haven't been able to find the answer yet...

**Comment by goord** [comment]
Hi Tommi the z-factor is usually not listed as a separate variable in the table, that's why for IFS I 'invent' new tasks for the surface pressure whenever necessary. Apparently, CMOR requires the z-factor always to be the time-averaged surface pressure, independent of the time operator of the 3D field...

**Comment by tommibergman** [comment]
But that it is defined in the table is exactly my problem since _ps_ is defined as _time1_ but cmor expects it  to be time when used in zfactor. If I define it as _time_ it will give error for not being _time1_ as it should for _ps_ and when I define it as _time_ zfactor-call will give an error. So neither one will work and in my view this is a problem in CMOR library itself.

**Comment by zklaus** [comment]
Just wanted to add that this currently prevents us from cmorizing the amip experiment (which could be the first to go all the way through to publication since it is, of course, atmosphere only, thus avoiding all the ocean problems, and is initialized from a reanalysis, thus not depending on any spin-ups).
This is because this issue not only prevents writing of some variables, but sends all the ece2cmor processes into a zombie state.

**Comment by goord** [comment]
Hi @zklaus does this issue still occur in your atmosphere-only cmorization? Can you send me the complete log of that then?

**Comment by goord** [comment]
As was suggested (here)[https://github.com/PCMDI/cmor/issues/430], we need to use "ps1" as the zfactor_name for the instantaneous surface pressure field. I will create a test for ifs using both an averaged and instantaneous model-level variable to see how this works out.

**Comment by tommibergman** [comment]
Okay, I think you are right. I understood this wrong earlier. It is confusing to use ps1 as this is not defined anywhere else, I would expect to have a variable called ps1 in the tables. But actually the ps in the table is ps1 since it has dimension time1.

**Comment by goord** [comment]
Hi Tommi, I fixed the problem for ifs in #423 so you can let that solution inspire you. I will remove the release label and use the tm5 instead,

**Comment by tommibergman** [comment]
Yes I did this already also. But CMOR library cannot handle 5 dimensions (lon,lat,lev,time, and lambda550nm) But they are working on it at PCMDI.

**Comment by treerink** [comment]
Which is covered by #421.

So closing this issue.
