### ISSUE TITLE
Handling of start-from-restart cases (one time step files)

### ISSUE THREAD

**Issue by ufladrich** [EC-Earth/ece2cmor3#430]
This is a follow-up issue to #413. The problem is that in some cases, the automatic detection of variable frequencies has a problem.

Citing @klauswyser:

> Indeed we were testing a new case: the start of a scenario experiment. A historical experiment ends in 2014 and is followed by several scenarios starting in 2015. The scenario experiments will receive new experiment names yet they don't make a cold start but use the last set of restart files from the historical run. This implies that the ICM*+201412 that are saved at the beginning of the scenario experiment are incomplete in the sense that they only contain 1 timestep, and I think this is where the logic breaks down. It's good if this can be solved.

**Comment by ufladrich** [comment]
For completeness, I cite @goord with a suggestion:

> Would it be an option to create symlinks to the december files in 2014 with the new experiment name? At least we don't have to equip ece2cmor3 to handle multiple experiment names.
> 
> The ppt files and data request both changed in the scenario runs w.r.t. the historical right?

**Comment by plesager** [comment]
Has anybody tested if prepending (copies or links with the correct experience name) the 2014-12 data  to the scenario run works?

**Comment by oloapinivad** [comment]
No experience yet sorry, personally I will try to use the initial conditions from the `libsave_ic` to sort this out.

**Comment by plesager** [comment]
Alright, then your start date will be 2015-01-01. For those who continue with the restart files from the historical run, it may be wise to restart on 2014-01-01 and cmorize from 2015-01-01. This is the only way to ensure that the same data set is available in 2014-12.

**Comment by klauswyser** [comment]
We have cmorized a case with a *new* experiment starting from the restart files of a previous experiment. Of course, it didn't work straight away, we had to do the following:

1.  add an output/ifs/001 directory with ICM*+000000 files. You can link to the ICM*+000000 files from the previous experiment, but you have to rename the links (because of the new experiment name).

2.  if your experiment starts with leg N than you have to create a new directory output/ifs/N-1 and **move** the first files (e.g. ICM*+201412) from output/ifs/N to output/ifs/N-1

After these changes everything worked fine.

**Comment by treerink** [comment]
Theis info has landed at the [wiki](https://github.com/EC-Earth/ece2cmor3/wiki): https://github.com/EC-Earth/ece2cmor3/wiki/Recommended-strategies.

So closing issue.
