### ISSUE TITLE
version directory

### ISSUE THREAD

**Issue by oloapinivad** [EC-Earth/ece2cmor3#492]
This is a question rather than an issue. 

Each time I run ece2cmor the versioning directory (e.g. `v20190613`) is created according to the present date.
This is okay, but when cmorization goes beyond midnight or it is done in two different days more directories will come. 

I am seeing this since I cmorize year by year in separate folders - I am doing it on the run and it is more convenient for archiving - so that the same variable will end up with several versioning dirs.

I remember I read once an issue related to this but I cannot find it: is this due to the directory structure I am using or is it a common issue? What is the official recommendation for this, i.e. should I use the version from the first year for the whole dataset?

Thanks for any help,
Paolo

**Comment by klauswyser** [comment]
The version is a real piece de résistance, causes lots of problems. Unfortunately there isn't much we can do about it, it is created automatically by the cmor3 library and cannot be set manually. Nevertheless, the [DRS controlling document](http://goo.gl/v1drZl) requests

> \<version\> has the form “vYYYYMMDD” (e.g., “v20160314”), indicating a representative date for the version.   Note that files contained in a single <version>  subdirectory at the end of the directory path should represent all the available time-samples reported from the simulation; a time-series can be split across several files, but all the files must be found in the same subdirectory.  This implies that <version> will not generally be the actual date that all files in the subdirectory were written or published.

which means that all files from a single experiment have to be collected in one single version directory. This means some additional manual processing of the output after ece2cmor3. I attach a [script](https://github.com/EC-Earth/ece2cmor3/files/3290044/create_release.sh.zip)
that creates a proper directory structure with configurable version and fills it with hard links to the cmorised files after ece2cmor. This works fine and fast as long as you stay on the same file and hard links work.

A consequence of the requirement that all files from a single experiment have the be in one directory is that if you happen to miss one or more years when publishing the first chunk you will have to publish the missing file(s) with the same version even if this may be much later.

Furthermore: what if a single file of a variable turns out to be corrupt or wrong? CMIP6 foresees the possibility to unpublish already published data. My interpretation of the citation above is that you then have to unpublish *all* files (years) with this variable of this experiment, and then republish with a new version number,

**Comment by oloapinivad** [comment]
Thanks Klaus, for both the explanation and the script. 
I guess the best approach is to produce all the data and then right before publication create the versioning directory.

**Comment by uwefladrich** [comment]
Just came across this issue. I attach another version of a script that fixes versions, just for the sake of choice ;-)


[versions.sh.txt](https://github.com/EC-Earth/ece2cmor3/files/3310681/versions.sh.txt)

**Comment by zklaus** [comment]
@oloapinivad can this be closed? Should we have better documentation for it?

**Comment by oloapinivad** [comment]
My only concern is to have a shared procedure for it. If we agree that we will set up a version that corresponds to the date of the publication, we can close it.

**Comment by treerink** [comment]
I used Uwe's script `versions.sh,` it seems to work fine (only if you want the correct leg number printen ahead you need a tiny hack for scenario restarted cases). I fortunately had only one version, so have not tested the -m case.

I actually plan to add here at the ece2cmor Github pages a small wiki part, so this kind of info can land in a wiki instead of being in an (closed) issue. And if no objection (maintenance) I would like to add a few of this scripts also here in ece2cmor, so it is all by hand, otherwise we make a reference. But next week ...

**Comment by uwefladrich** [comment]
The rules above require very little, namely that all files for one table-variable combination for the same experiment must have the same version. As you said, this is not automatically ensured by the cmorisation process, you have to fix it after ece2cmor and before publication.

I think it has emerged from previous discussions that we may want to go a little longer than what the rules require: all table-variables combinations for the same experiment should have the same version. Note that this should arguably be the case even when the data is published in different chunks. For example, we publish years 1-500 of piControl now and later years when we have time. Nevertheless, we'll still use the same version for the second chunk of piControl publication.

_Which_ version (date) one is using is secondary, it should _represent_ the data of data production/cmorisation/publication. We use the cmorisation date (or somewhere nearby).

Does that make sense?

**Comment by zklaus** [comment]
This sounds all good to me.

As for which should be the exact version, @oloapinivad note that it will be basically impossible to know when exactly the data manager can publish something, so choosing the date of publication is difficult.
But something nearby is good.

To clarify what @uwefladrich said: Even when we publish in chunks, all chunks *definitely must* have the same version.

**Comment by oloapinivad** [comment]
Ok, agreed on the strategy - it will be nice to have this on the wiki:
- Publish all the data from the same experiment under the same version
- Use a version that is nearby the date of the publication.
- (optional) Use the `versions.sh` script to handle multiple versions

Anything else?

**Comment by uwefladrich** [comment]
@zklaus ahh, you're right, in my example it is _must_, not _should_, because we are extending the time series. If you chose to publish some variables later, it would be possible to use another versions, but we don't want to do that.

**Comment by zklaus** [comment]
Just wanted to mention PCMDI/cmor#267. There seems to be some room for clarification in cmor. However, I think our strategy should work well.

**Comment by treerink** [comment]
Also this has landed in the wiki: https://github.com/EC-Earth/ece2cmor3/wiki/Recommended-strategies

So closing this issue.
