### ISSUE TITLE
patch to be able to cmorize variables not in <model>par.json

### ISSUE THREAD

**Issue by etiennesky** [EC-Earth/ece2cmor3#528]
The following patch can be used to cmorize variables not defined in lpjgpar.json. 

I n my case this is burntFractioAll, which is no yet produced correctly my LPJG (soon will be). I have modified LPJG to ouput this variable at monthly timescale.

Although burntFractioAll is defined in the tables, it is no t in lpjgpar.json. WIth  this patch, any variable found in the tables can be cmorized, provided there is no operation needed on the data.

```diff
diff --git a/ece2cmor/ece2cmor3/taskloader.py b/ece2cmor/ece2cmor3/taskloader.py
index 7247b09f..b74cdf03 100644
--- a/ece2cmor/ece2cmor3/taskloader.py
+++ b/ece2cmor/ece2cmor3/taskloader.py
@@ -542,7 +542,12 @@ def create_tasks(matches, active_components):
             continue
         parblocks = model_vars[model]
         for target in targets:
-            parmatch = [b for b in parblocks if matchvarpar(target, b)][0]
+            #parmatch = [b for b in parblocks if matchvarpar(target, b)][0]
+            parmatch1 = [b for b in parblocks if matchvarpar(target, b)]
+            if len(parmatch1) == 0:
+                parmatch = { "source": target.variable, "target": target.variable }
+            else:
+                parmatch = parmatch1[0]
             if parmatch.get("table_override", {}).get("table", "") == target.table:
                 parmatch = parmatch["table_override"]
             task = create_cmor_task(parmatch, target, model)
```

**Comment by goord** [comment]
I see no harm in this, but why don't you create your own lpjgpar.json with this variable etienne? You can force ece2cmor3 to use a custom parameter table with the --lpjgpar=<your file> option...

**Comment by etiennesky** [comment]
Hi, I thought it easier for any future additions to allow any variable that is output and in the cmip6 tables to be supported without editing lpjgpar.json.

**Comment by goord** [comment]
Hi etienne I'm a bit reluctant to implement your idea because @treerink has been working on quite an extensive system to monitor which variables are supported/to be supported/ignored etc., and this modification could break this. Moreover, it is a priori not clear to ece2cmor3 which model component a variable belongs to, so the modification above can cause crashes for e.g. IFS variables no?

**Comment by treerink** [comment]
Agree with Gijs. Closing this.

**Comment by etiennesky** [comment]
I admit I am at a loss why ece2cmor3 always needs "passthrough" variables in nemopar.json and lpjgpar.json. This makes things a bit cumbersome for users and forces a strong dependency between the output control files and the ece2cmor3 version.

For example, the recent changes to the LPJG and PISCES definitions in the ctrl files absolutely required the same trivial changes to nemopar.json and lpjgpar.json.

Also it doesn't help that the cryptic message given when ece2cmor crashes when those variables are requested (but not in nemopar.json of lpjgpar.json) is pretty hard to understand.

```
Traceback (most recent call last):
  File "./ece2cmor.py", line 157, in <module>
    main()
  File "./ece2cmor.py", line 123, in main
    check_duplicates=True)
  File "/gpfs/scratch/cns61/cns61456/a2f4/auto-ecearth3/ece2cmor/ece2cmor3/taskloader.py", line 74, in load_tasks
    return create_tasks(filtered_matches, get_models(active_components))
  File "/gpfs/scratch/cns61/cns61456/a2f4/auto-ecearth3/ece2cmor/ece2cmor3/taskloader.py", line 536, in create_tasks
    parmatch = [b for b in parblocks if matchvarpar(target, b)][0]
IndexError: list index out of range
```
I am sorry but I still fail to understand the fundamental need for this formalism when the variables have the same name and no conversion is needed. For IFS and some variable I get the point, but not for these passthru variables.  A quick look into nemopar.json reveals that no transformations or name changes are done, as for lpjgpar.json a few variables need the frac2percent conversion.

Nothing to get concerned about now, just food for thought for next release.

**Comment by treerink** [comment]
Well partly this is historical (for the old ec-earth nemo names) and partly because it is easy to have all in the same way. I think, though there are a few exceptions even in nemo & lpj-guess where this feature is used.

We decided that changing it is not a high priority and worth the effort, many other issues have higher prio.

**Comment by etiennesky** [comment]
I understand - will think of something in the near future to propose

**Comment by goord** [comment]
Hi @etiennesky one of the reasons for having this is to have an administration of which cmor-data we can expect to be output by NEMO/LPJG and which we don't, and as such to have predictable behavior instead of a tool that grabs any data it deems being appropriate to produce a field (on the basis of it having the same variable name for instance).

The error you encounter should however not be there. It can mean 2 things (@treerink correct me if I'm wrong)
* You are loading a data request (either json or excel, with table+variable info via the ``--drq`` option) with a variable that is not in the ignored or identified missing files. In that case we have a problem as a dev community because this variable should be identified, i.e. either supported, ignored or put on the 'waiting list' (identified missing),
* You have edited a varlist json of the form component : table : variables and are loading it with the ``--varlist`` option in which case we assume the variable is supported and in the parameter table. Maybe in this case we should let the tool proceed as if the variable is supported, but that would open up a backdoor and the risk is that the identified-missing administration becomes outdated without us knowing it...

In any case, yes it is complex, perhaps a bit too much and we can simplify things. 
I will in any case catch the error you report and print something understandable instead.

**Comment by etiennesky** [comment]
Hi @goord the error happened because I was using an older version of ece2cmor, without the new variables in nemopar.json and lpjgpar.json recently introduced in trunk.

I can try using the old version and just adding the new vars to the .json files and see if that improves.

I will also see if I can reproduce that cryptic error with the new ece2cmor without the variables in the .json files. I think this kind of error should be avoided - even if the variables are not supported.

**Comment by goord** [comment]
Hi Etienne I just pushed a fix for the crash, replacing it with a human-readable error message. But that will be for next release.
