### ISSUE TITLE
3D pextra variables are not added to correct ouput category in IFS ppt's

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#558]
I am testing one PEXTRA variant of the control output files, namely:

    ctrl/cmip6-output-control-files-pextra/CMIP/EC-EARTH-AerChem/cmip6-experiment-CMIP-piControl

The following group of variables:

- 126020, 126022, (ACI)
- 126094, 126095, 126099, 126106, 126110, (LBUD23)
- 126129, (DYNVAR)

are added to the `MFP3DFS` (model levels) and not to `MFP3DFP` (pressure levels).  Since we output only on pressure levels, we should move (or add) these variables to `MFP3DFP`. The lists above are subset of what could be output from each group (ACI, LBUD23, and DYNVAR).

**Comment by treerink** [comment]
In the file:
```
ece2cmor3/ece2cmor3/resources/grib_codes.json
```
these codes are currently part of` "MFP3D"`.

@goord where is the distinction between model levels and pressure levels made? In `drq2ppt.py`?

**Comment by treerink** [comment]
This case can be fast tested with:
```
./drq2ppt.py --drq cmip6-data-request/cmip6-data-request-m=AerChemMIP.CMIP-e=piControl-t=1-p=1/cmvme_ae.cm_piControl_1_1.xlsx
```
The log message for `126020` from `drq2ppt` is:
```
Adding grib code 20.126 to MFP3DFS 6hr ppt file for variable cdnc in table AERmon
```

With that it seems that because for this variable `zaxis` is in `cmor_target.model_axes` it does not add it to `MFP3DFP` anymore, because of the `elif`. See:
```python
                    if code in cmor_source.ifs_source.grib_codes_3D:
                        if zaxis in cmor_target.model_axes:
                            log.info("Adding grib code %s to MFP3DFS %dhr ppt file for variable "
                                     "%s in table %s" % (str(code), freq, task.target.variable, task.target.table))
                            mfp3dfs.append(code)
                            alevs.extend(levs)
                        elif zaxis in cmor_target.pressure_axes:
                            log.info("Adding grib code %s to MFP3DFP %dhr ppt file for variable "
                                     "%s in table %s" % (str(code), freq, task.target.variable, task.target.table))
                            mfp3dfp.append(code)
                            plevs.extend(levs)
```

It seems to me that if we change the `if-elif` to `if, if` it will end up in both `MFP3DFS` and `MFP3DFP`. 

Is there a reason that it should be a if-elif-elif-else? Or can I change it and take care of the else situation?

**Comment by goord** [comment]
The question here is: @plesager are those variables requested on model levels or pressure levels?

@treerink the logical branch you point out makes perfect sense to me: for a given requested 3D variable (target), it must be either requested on model levels or pressure levels or height levels, otherwise we throw an error.

**Comment by noije** [comment]
@goord: CNDC is requested at model levels and as monthly mean. It needs to be calculated in the postprocessing from the two provided CDNC related variables: the first (126.020) being the accumulated value of CDNC times liquid cloud time, the second (126.022) the accumulated liquid cloud time.

These two variables first have to be accumulated over all output intervals for each month. Then, CDNC (actually in-cloud CDNC) follows by division of the two accumulated variables.

**Comment by plesager** [comment]
Yes, data request says alevel, so this should be on model levels. It just needs to be activated, Thomas will open another issue for that.
