### ISSUE TITLE
phasing out LFS

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#734]
Again we want to get rid of LFS in ece2cmor3 (like in #234). This means that all data under `ece2cmor3/test/test_data/` has to be moved to the [b2share ece2cmor3-data](https://b2share.eudat.eu/records/f7de9a85cbd443269958f0b80e7bc654).

The total amount of test data is about 730 MB, a large part concerns the LPJG test data (#219) and though there seems to be added a test varlist `ece2cmor3/ece2cmor3/resources/test-data-request/varlist-lpjg.json` it seems that never a kind of `ece2cmor3/test/lpjg2cmor_test.py` has been created.

The idea now is first to:
-  add the test-data-* datasets to b2share
-  to add the b2share auto checking whether these test-data-* have been downloaded or not
-  to add these files to the ece2cmor3/download-b2share-dataset.sh script

Thereafter:
- remove the entire git history of LFS for ece2cmor3

**Comment by goord** [comment]
Looking around on the internet, it actually seems really hard to remove the git LFS files fully from the history to reduce quota. Github itself recommends removing the entire repo (!) or paying up... I'm quite regretting to have initiated this LFS thing (especially since it isn't really used right now...)

**Comment by goord** [comment]
By the way, @treerink and @zklaus you can define the environment variable ```GIT_LFS_SKIP_SMUDGE=1``` to skip all LFS downloading LFS files when pulling, so you can keep working with the code in the repo

**Comment by zklaus** [comment]
Hm. To me, there seems to be quite some misunderstanding. The whole point of LFS is not to have large files in the repo. LFS managed files should take up virtually no space in the repo, so let's have a look:

The following are all the objects (blobs) in the repo that take up more than 1MiB on disk
```
bb8dcb0278f4  1.7MiB test/test_data/ifsdata/3hr/ICMSHECE3+199001
941b21b65f88  8.3MiB test/test_data/ifs/ICMGGpl01+199001
0247c9a0d074   14MiB test/test_data/ifsdata/6hr/ICMGGECE3+199001
9b42e6160b3a   29MiB test/test_data/ifsdata/3hr/ICMGGECE3+199001
6adc648198ea   30MiB test/test_data/ifs/ICMSHpl01+199001
042b446dd504   76MiB test/test_data/ifsdata/6hr/ICMSHECE3+199001
```
The first column is the objectname (the hash), the second the size on disk, and the third the path.

Let's start with the largest:
```
$ git log --oneline test/test_data/ifsdata/6hr/ICMSHECE3+199001
74ec60b save local for later
d85e949 Added spectral file lfs tag
23967d8 Updated cmip tables
19d67a0 Added missing pressure level 850 for u and v to test data
68599f6 Fixed pressure level issues
d6b2e18 Added ifs test data
```
Alright, this path was touched in six commits. Let's see in which the specific, large blob is involved.
```
$ TARGET=042b446dd5043149074407fa3233a932bd1a532d
$ for CANDIDATE in $(git log --pretty=format:%H test/test_data/ifsdata/6hr/ICMSHECE3+199001); do FOUND="$(git ls-tree -r -t $(git show --quiet --format='%T' $CANDIDATE) |egrep $TARGET)"; if [ -n "$FOUND" ]; then git log -n 1 $CANDIDATE; fi; done

commit d6b2e183f3c624ac8b3575ef65b6065d4ef1ea38
Author: gvdoord <g.vandenOord@gmail.com>
Date:   Mon Mar 27 18:28:55 2017 +0200

    Added ifs test data
```
Ok, so the problematic blob appears in only one commit from March 2017.
By the way, when did we introduce LFS?
```
$ git log -- .gitattributes

commit 85b72028dbdb5c72c384572e79ad3006bce9a51f
Author: gvdoord <g.vandenOord@gmail.com>
Date:   Tue Aug 8 00:39:12 2017 +0200

    Added large atmosphere data files to lfs
```
Aha, in August 2017. That explains a significant chunk of the space needed.
I checked for some of the other files; the situation seems to be similar.

So I don't think the problem of the large repo is due to lfs, but rather due to large files added before the adoption of lfs. Those six blobs account for just under 160MiB of the 181MiB which is the size of the repo (the .git directory, obviously the working directory size is less relevant or predictable).

**Comment by zklaus** [comment]
@goord, could you clarify what you mean by
> Looking around on the internet, it actually seems really hard to remove the git LFS files fully from the history to reduce quota. Github itself recommends removing the entire repo (!) or paying up...

What documentation are you referring to and what is the actual problem with simply removing the files? This should not be a problem since the access to those files (and therefore remaining quota) is only required when *checking out a tree that contains them*.

**Comment by goord** [comment]
Ideally, we remove to he files from the history in such a way that git LFS doesn't see the objects anymore, and a fresh checkout doesn't add to the bandwidth quota.

**Comment by zklaus** [comment]
If you just normally remove the files in a new commit, a fresh checkout (i.e. updating the working directory to a specific state) to a state without the files will not add to the bandwidth. I don't think any dark (history rewriting) magic is required here.

**Comment by goord** [comment]
Well too hat would be perfect, let's find out!

**Comment by goord** [comment]
I removed the test data directly on the master branch.
A fresh clone is slow, but working again. Seems you're right @zklaus!

**Comment by zklaus** [comment]
Cheers :smile: 

Re the slowness of cloning: As I indicated above, there are a few large files lurking in the history that had been added before the adoption of LFS. It might make sense to get rid of them, but that is indeed a bit more involved.

**Comment by goord** [comment]
I guess I was confused about something I read about removing privacy-sensitive data from the LFS history. But we do not need to clean up the LFS history (unless we all go try checkout old revisions). Removing the big blobs from the repo history is something we can do in another issue.

@treerink I guess we don't need to create anything on b2share now, the lpjg files are still on git LFS and in case anyone needs them, they can be downloaded with e.g. an old tag

**Comment by zklaus** [comment]
Agree on tackling the big blobs in another issue. The reason to put the files on b2share (or make them available in another way) would be to allow any tests that need them to run. I am not sure what the state of the tests is, though.

**Comment by goord** [comment]
There are no tests anymore using the test data. I converted the data to csv files contanining only the grib record metadata and those are used in tests

**Comment by zklaus** [comment]
Perfect. In that case they can and should really just go.

**Comment by goord** [comment]
ok closing the issue then
