### ISSUE TITLE
Wrong skin temperature

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#744]
The skin temperature in EC-Earth is incorrect. See discussion in https://dev.ec-earth.org/issues/1188. Apparently the fix consists in correcting the grib code in the `ifspar.json`.

**Comment by treerink** [comment]
Fixed in 37ae5ef, note that with this fix many ppt files change because grib code `235` is added, however in another part of the files the `235` is already included due to a request of other variables. Also all request-overview files change. 

New output-control-files will be provided in an ECE branch (on top of changes due to the license change and changes due to the python3 transition).  Further discussion of the treatment of wrong published data (errata) and an eventual fix with cmor-fixer will continue in [ece portal issue 1188](https://dev.ec-earth.org/issues/1188).
