### ISSUE TITLE
New grib codes for clear-sky downwelling radiative fluxes at the surface (rsdscs and rldscs)

### ISSUE THREAD

**Issue by plesager** [EC-Earth/ece2cmor3#772]
See [this discussion](https://dev.ec-earth.org/issues/1237) for details. Boils down to:

- new recipe to retrieve these two variables (relatively urgent but rather straightforward to fix)
- new grib codes for IFS ppt files that request them (that's an EC-Earth3 issue)

**Comment by plesager** [comment]
Another question: do we make it possible to cmorize the two variables according to either the old or the new recipes? I propose  that we don't. If users really want to cmorize these two variables and the corresponding ppt files assume the old recipes (eg, old branches not updated or re-cmorizing existing output), they could:
- use the old ifspar.json (we could provide an old version along the new one)
- downgrade to ece2cmor 2.1
- simply remove the two variables (buggy anyway) from the data request

Any thought ? @klauswyser @etiennesky ?

**Comment by klauswyser** [comment]
> Another question: do we make it possible to cmorize the two variables according to either the old or the new recipes? I propose that we don't.

Why not? There will be data requests for these variables. OK, we know that they are buggy, but I don't think they are systematically wrong, or? So yes, we should have an errata on es-doc saying that there still is a problem, but we shouldn't stop publishing the fixed variables, wouldn't you agree?

I also wouldn't remove the old GRIB parameters from ifspar.json. We (and others) could still have tons of uncmorised simulations lying aroud that we may want cmorise at some point. All our previous runs were cmorised with the erroneous clear-sky variables, so why not continue? Unless somebody shows that we have a systematic bias over extended areas. What I would change though are the ppt files (probably by changing genecec) so we don't produce more instances of the old version in new experiments.

My 2 cents.

**Comment by plesager** [comment]
Actually there is already a useful option when calling `ece2cmor`:
```
> ece2cmor -h
[...]
 --ifspar.json FILE.json     ifs variable table (optional) (default: .../mamba/envs/ece2cmor3/lib/python3.11/site-packages/ece2cmor3/resources/ifspar.json)
```
Users who want to cmorize the two clear-sky variables the old way can use that option to point to an alternate ifspar.json we provide.

**Comment by klauswyser** [comment]
Sounds fine to me.

Den 16 nov. 2023 16:04 skrev "P. Le Sager" ***@***.***>:

Actually there is already a useful option when calling ece2cmor:

> ece2cmor -h
[...]
 --ifspar.json FILE.json     ifs variable table (optional) (default: .../mamba/envs/ece2cmor3/lib/python3.11/site-packages/ece2cmor3/resources/ifspar.json)


Users who want to cmorize the two clear-sky variables the old way can use that option to point to an alternate ifspar.json we provide.

**Comment by plesager** [comment]
Changes to cmorize rldscs/rsdcs from the new grib codes has been pushed. See d0a134c. I double checked the Amon results (TOP="old" and BOTTOM="new" in each figure). The old results were produced by using the option:
`ece2cmor ... --ifspar.json '<path to ece2cmor installation>/ece2cmor3/ece2cmor3/resources/ifspar-old-clear-sky.json'`

- **LW** (I kept the original data range to show how it differs over a full year)
![lw-old-vs-new](https://github.com/EC-Earth/ece2cmor3/assets/11032052/229e54be-0e99-4a73-b719-b44b47369138)

- **SW** (Note the huge range in the old data) 
![sw-old-vs-new](https://github.com/EC-Earth/ece2cmor3/assets/11032052/a6ad060a-0a80-475d-a407-961302411be8)
and the same plots but the old dataset is plotted within the same range as the new one:
![sw-old+scaled-vs-new](https://github.com/EC-Earth/ece2cmor3/assets/11032052/6407fc9c-06bf-484b-b553-0b7e3a9962bb)

**Comment by klauswyser** [comment]
Nice results. They just show the 1st month (January), not an annual avg, right?

There is quite an impact in SW over Antarctica, do we understand where this comes from?

**Comment by plesager** [comment]
Yes these plots are just one time step from the monthly averages output. As for the spurious SW data over Antarctica, I think the best explanation we have so far is from @noije: https://dev.ec-earth.org/issues/826#note-2.

**Comment by klauswyser** [comment]
Twan certainly has a point that the clear-sky surface albedo is different from the all-sky albedo, and that the assumption about the value for rsdscs when rss is small could be problematic. However, I'm not sure if this really the source of the problem described here, if it isn't rather a more generic problem of the IFS radiation scheme in which net fluxes can become larger than donwelling fluxes? @tommibergman suggested a fix for this (https://dev.ec-earth.org/issues/1242) that does the trick, but of course it doesn't help for simulations that have already been done.

**Comment by plesager** [comment]
Interesting hypothesis. The previous run was done with the quadratic interpolation between radiation and grid point grids, since I'm using a CMIP6 branch. From that run, I cmorized twice to compare the effect of switching to the new diagnostic (and only that). I ran another experiment with the linear interpolation this time, and again cmorized twice with the two diagnostics. So now I have 4 different outputs from either linear or quadratic interpolation and from either the old ece2cmor3 formula or the new inline computation. Results are in [the attached improved-rsdsc.pdf](https://github.com/EC-Earth/ece2cmor3/files/13447999/improved-rsdsc.pdf). In short: the linear interpolation removed the largest spurious values (max range lowered from 2760 to 662 W/m2) but you can see areas where it is still quite different from the new diagnostic (and where the original ece2cmor3 formula fails).

**Comment by klauswyser** [comment]
Cool! Do we still have points with ``rsdscs > rsdt`` with linear interpolation? Of course, this doesn't help for runs that have been made already for CMIP6, just good to know (i.e. for ECE4).

**Comment by plesager** [comment]
With linear interpolation, the ece2cmor3 formula still brings up points with `rsdscs > rsdt`. It appears every month (red points), for example in march:
![Screenshot from 2023-11-23 17-00-13](https://github.com/EC-Earth/ece2cmor3/assets/11032052/07b127bd-47dc-4a21-8935-5aa7a5a8cd83)
In July, it is over almost the entire Greenland.

However, with the linear interpolation and using the inline computation from Declan, we never see `rsdscs > rsdt`.

**Comment by treerink** [comment]
A wiki page [Activate the old clear sky (rsdscs & rldscs) output](https://github.com/EC-Earth/ece2cmor3/wiki#activate-the-old-clear-sky-rsdscs--rldscs-output) has been added, so we have a point to refer to how to cmorise `rsdscs` & `rldscs` output which has been run with the old ECE configuration (i.e. the current / old ppt files, which will be replaced soon): this page simply shows how to run the tiny script for this.

(Note: The `switch-on-off-old-clear-sky-output.py` also could be used to rerun `genecec` in the old state in order to produce the ppt files corresponding to the previous erroneous  `rsdscs` & `rldscs` output implementation, however I do not expect this will be ever necessary.)

**Comment by treerink** [comment]
I have run `genecec` for the `control-output-files/cmip6` part and will upload this to the ECE svn repository in a branch. What entirely drops out is `Surface net long-wave (thermal) radiation, clear sky` (grib code `211`). In other experiments more grib codes drop out in various `control-output-files` because other grib codes in the two previous `rsdscs` & `rldscs` expressions are simply not asked by other requested variables: This might apply to one or more of the following grib codes:
``` 169,175,176,177,210,211```
which were within the two previous expressions:
```
rsdscs:  code name = 132.129, expression = (var176<=1e-10)*var210+(var176>1e-10)*var210*var169/var176
rldscs:  code name = 104.129, expression = var211-var177+var175
```

Despite the previous naming convention, in which a distinction was made between `cmip6` and `cmip6-pextra` `control-output-files` and thus only the  `cmip6-pextra`  `control-output-files` contained PEXTRA table 126 grib codes, now for `rsdscs` & `rldscs` the 126 table grib codes `126001` and `126002` are also used in the new  `cmip6`  `control-output-files` which will be available soon. Although this two `126` codes will come in to the `cmip6`  `control-output-files` part (due to which the general naming fits less well) we keep the rest of the set up the same, this is because the other PEXTRA table 126 related output requires more sophisticated expertise in configuring the ECE `namelists` .

**Comment by treerink** [comment]
The `772-new-grib-codes-for-clear-sky-downwelling-radiative-fluxes-at-the-surface-rsdscs-and-rldscs` branch has been merged into the master. The corresponding new `control-output-files` will be committed to the ECE3 svn repository in a next `control-output-files` branch.
