### ISSUE TITLE
lpjg cmorisation for OptimESM fails

### ISSUE THREAD

**Issue by klauswyser** [EC-Earth/ece2cmor3#798]
Lars I think you branched off from a not update master. I tried to merge the master in your branch but meanwhile you made a commit, so I now first have to solve the git mixed up state.

_Originally posted by @treerink in https://github.com/EC-Earth/ece2cmor3/issues/789#issuecomment-1929357687_
 
@treerink, @nierad: let's start a new, fresh issue with only LPJG on our minds :-)

**Comment by klauswyser** [comment]
I have pulled Lars' branch and it works much better, now ``fco2nat`` is produced. But then I get a stop with ``cLand_1st``, probably related to the fact that this is a non-CMIP6 variable. Can't this variable be added to table LPJGmon instead?


````
INFO:ece2cmor3.lpjg2cmor: CMORizing variable cLand_1st in table Emon from cLand_1st in file cLand_1st.out...

^[[2;31;47mC Traceback:
! In function: ^[[0m

^[[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: var_id cannot contain _ you passed: cLand_1st (table: Emon). Please check your input tables
!
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m
````

**Comment by klauswyser** [comment]
``fco2nat`` is negative over land and tropical ocean, and positive over mid- and high latitude oceans. Does this make sense? You can have a look yourself on Bi: /nobackup/rossby27/proj/optimesm/sm_wyser/ece2cmor3/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-CC/historical/r1i1p1f1/Amon/

**Comment by nierad** [comment]
Thanks, Klaus. It seems to have worked properly. If I am not mistaken, the sign of the ocean flux should be reversed, as e.g. the northern Atlantic should be releasing CO2 in summer  and taking it up otherwise, no?

**Comment by klauswyser** [comment]
Well, phytoplankton grows in summer, taking up CO2. On the other hand oceans release CO2 when the water gets warmer. Frankly, I cannot tell right away, maybe @etiennesky could help? There is also quite a difference in magnitude of CO2 fluxes over land and ocean, does this make sense?

[``fco2ant`` and ``fco2nat`` examples](http://exporter.nsc.liu.se/ef5b3238134b4f1aad3a3182cb5198a8)

**Comment by nierad** [comment]
Well, I don't know anything about the ocean fluxes....
________________________________
Von: klauswyser ***@***.***>
Gesendet: Dienstag, 6. Februar 2024 16:37
An: EC-Earth/ece2cmor3 ***@***.***>
Cc: Lars Nieradzik ***@***.***>; Assign ***@***.***>
Betreff: Re: [EC-Earth/ece2cmor3] lpjg cmorisation for OptimESM fails (Issue #798)


Well, phytoplankton grows in summer, taking up CO2. On the other hand oceans release CO2 when the water gets warmer. Frankly, I cannot tell right away, maybe @etiennesky<https://github.com/etiennesky> could help? There is also quite a difference in magnitude of CO2 fluxes over land and ocean, does this make sense?

fco2ant and fco2nat examples<http://exporter.nsc.liu.se/ef5b3238134b4f1aad3a3182cb5198a8>

**Comment by nierad** [comment]
Hi Etienne,

well, that is exactly the point. The sign needs to be changed. Fco2nat is negative, because gfco2 has simply been added to fco2nat(land). Would you be happy with it the other way round?

Cheers, Lars
________________________________
Von: Etienne Tourigny ***@***.***>
Gesendet: Dienstag, 6. Februar 2024 17:38
An: EC-Earth/ece2cmor3 ***@***.***>
Cc: Lars Nieradzik ***@***.***>; Assign ***@***.***>
Betreff: Re: [EC-Earth/ece2cmor3] lpjg cmorisation for OptimESM fails (Issue #798)


Yes, I think there is a mistake there. fgco2 is defined as "Surface Downward Mass Flux of Carbon as CO2" and fco2nat is defined as "Surface Carbon Mass Flux into the Atmosphere"

Normally the equatorial East Pacific outgasses CO2, so this means negative fgco2 , and we should have positive fco2nat, which is not the case in the file you provided. Can you upload the fgco2 output ?

**Comment by etiennesky** [comment]
Also @treerink  in order to save the fluxes only from LPJG in the past we added a new (non-CMIP6) fco2nat entry in the Lmon table, with fco2nat in Amon being the sum of fluxes from LPJG and NEMO/PISCES. But I think you added a custom LPJG table, so we could add it there ?

**Comment by etiennesky** [comment]
> Also @treerink in order to save the fluxes only from LPJG in the past we added a new (non-CMIP6) fco2nat entry in the Lmon table, with fco2nat in Amon being the sum of fluxes from LPJG and NEMO/PISCES. But I think you added a custom LPJG table, so we could add it there ?

in summary, we should 

1) add fco2nat to the LPJGmon table
2) reverse the sign of fgco2 when adding it to fco2nat in the Amon table

**Comment by nierad** [comment]
Ok, I'll change the sign for gfco2.  Klaus, would you check my changes with your CDO-expert eye, please. It is in line  630 of lpjg2cmor.py
________________________________
Von: Etienne Tourigny ***@***.***>
Gesendet: Dienstag, 6. Februar 2024 18:18
An: EC-Earth/ece2cmor3 ***@***.***>
Cc: Lars Nieradzik ***@***.***>; Assign ***@***.***>
Betreff: Re: [EC-Earth/ece2cmor3] lpjg cmorisation for OptimESM fails (Issue #798)


yes, I meant to say "I think there is a mistake in ece2cmor".

**Comment by etiennesky** [comment]
> Ok, I'll change the sign for gfco2. Klaus, would you check my changes with your CDO-expert eye, please. It is in line 630 of lpjg2cmor.py

I think this would require a new argument "scale_factor" in add_nemo_variable (default value of 1, and it would be  -1 when calling it for this variable.

```
if not add_nemo_variable(task, ncfile, "fgco2", "1m", -1):
```

 Then you would need to change the cdo command as such : 

```
os.system("CDO_REMAP_NORM=destarea cdo -L invertlat -mulc,"+scale_factor+" -setmisstoc,0 -remapycon,"+remap_grid+" -selindexbox,2,361,2,292 -mul "+interm_file+" "+nemo_maskfile+" "+nemo_ofile)
```

**Comment by nierad** [comment]
I did it similarly but without the scale_factor
I was under the impression that, now that the file is fco2nat, it is clear because all of it should be "Surface Carbon Mass Flux into the Atmosphere Due to Natural Sources [kgC m-2 s-1]", Doesn't that suffice?
________________________________
Von: Etienne Tourigny ***@***.***>
Gesendet: Dienstag, 6. Februar 2024 18:26
An: EC-Earth/ece2cmor3 ***@***.***>
Cc: Lars Nieradzik ***@***.***>; Assign ***@***.***>
Betreff: Re: [EC-Earth/ece2cmor3] lpjg cmorisation for OptimESM fails (Issue #798)


Ok, I'll change the sign for gfco2. Klaus, would you check my changes with your CDO-expert eye, please. It is in line 630 of lpjg2cmor.py

I think this would require a new argument "scale_factor" in add_nemo_variable (default value of 1, and it would be -1 when calling it for this variable.

if not add_nemo_variable(task, ncfile, "fgco2", "1m", -1):


Then you would need to change the cdo command as such :

os.system("CDO_REMAP_NORM=destarea cdo -L invertlat -mulc,"+scale_factor+" -setmisstoc,0 -remapycon,"+remap_grid+" -selindexbox,2,361,2,292 -mul "+interm_file+" "+nemo_maskfile+" "+nemo_ofile)

**Comment by etiennesky** [comment]
> I did it similarly but without the scale_factor I was under the impression that, now that the file is fco2nat, it is clear because all of it should be "Surface Carbon Mass Flux into the Atmosphere Due to Natural Sources [kgC m-2 s-1]", Doesn't that suffice?

My intention was to have something generic, hence if you hard-code a multiplicative factor this should be documented in the code.

Sorry, but I don't understand your comment about "Doesn't that suffice?"

**Comment by nierad** [comment]
I think I don't understand your comment either. You do hard-code the factor too. Just in a different spot. And of course, I will document it.

**Comment by etiennesky** [comment]
> I think I don't understand your comment either. You do hard-code the factor too. Just in a different spot. And of course, I will document it.

My point is that we don't need to multiply by -1 all variables we could combine, only this specific one.  But anyway I don't think we will ever use this for other variables.

**Comment by nierad** [comment]
No, I don't think so either. But, of course, I  will make the code as transparent as possible, i.e. on a scale of 0-100 encrease it from 2 to 3...
________________________________
Von: Etienne Tourigny ***@***.***>
Gesendet: Dienstag, 6. Februar 2024 18:40
An: EC-Earth/ece2cmor3 ***@***.***>
Cc: Lars Nieradzik ***@***.***>; Assign ***@***.***>
Betreff: ***SPAM*** Re: [EC-Earth/ece2cmor3] lpjg cmorisation for OptimESM fails (Issue #798)


I think I don't understand your comment either. You do hard-code the factor too. Just in a different spot. And of course, I will document it.

My point is that we don't need to multiply by -1 all variables we could combine, only this specific one. But anyway I don't think we will ever use this for other variables.

**Comment by treerink** [comment]
> I have pulled Lars' branch and it works much better, now `fco2nat` is produced. But then I get a stop with `cLand_1st`, probably related to the fact that this is a non-CMIP6 variable. Can't this variable be added to table LPJGmon instead?

Yes adding to LPJGmon is possible for `cLand_1st`  (I have to read the rest of this issue in more detail whether you made different plans meanwhile). 

You have to **rerun** before cmorisation for the OptimESM case:
```
./add-lpjg-cc-diagnostics.sh
```
And in the co2box branch you have to **rerun** these two scripts:
```
./add-lpjg-cc-diagnostics.sh
./add-variables-for-co2box.sh
```
You can revert the Table changes by:
```
./revert-nested-cmor-table-branch.sh
```
which is not necessary when rerunning them (but also does not harm).

All scripts need to be run from the dir:
```
ece2cmor-root-dir/ece2cmor3/scripts/
```

**Comment by treerink** [comment]
> Also @treerink in order to save the fluxes only from LPJG in the past we added a new (non-CMIP6) fco2nat entry in the Lmon table, with fco2nat in Amon being the sum of fluxes from LPJG and NEMO/PISCES. But I think you added a custom LPJG table, so we could add it there ?

yes

**Comment by klauswyser** [comment]
BTW: to which table we add ``cLand_1st`` is just a matter of taste (yet there are bad tastes ;-)) but the error mesage above points to a more fundemantal problem: underscores aren't allowed in any CMIP names! We will have to rename ``cLand_1st`` ro something else. Not sure if this can be handled by ece2cmor, or if this has to be changed in the LPJG output already.

**Comment by treerink** [comment]
Oh yes underscores are not allowed!, I forgot about that.

Ok I will change it at the ece2cmor3 side in: `cLand1st`

So which table? I need a decision, I don't care, I can easily add it to the LPGmon table, but also leave it as it is. If we like it in the LPJG group it's totally fine with me (only can not be published on a ESGF node like the other LPJG table ones).

**Comment by treerink** [comment]
From the `ece2cmor3` side it is now `cLand1st` (again **rerun** : `./add-lpjg-cc-diagnostics.sh`).

**Comment by klauswyser** [comment]
LPJG doesn't work any longer because ``cLand_1st`` has been changed to ``cLand1st`` in ctrl/output-control-files/optimesm/lpjg_cmip6_output.ins:

This may be OK for the filename "cLand1st_monthly.out" but the variable ``file_cLand1st_monthly`` is unknown to LPJG. One solution (but not tested) could be
````
file_cLand_1st_monthly "cLand1st_monthly.out"
````
but that would break the conventions on how files and variables should be named.

To further increase confusion, both ecearth.ins and global.ins still contain
````
file_cLand_1st_monthly "cLand_1st_monthly.out"
````
I guess this requires a more in-depth clean-up on the LPJG guess side. Since @treerink already has changed the ece2cmor3 side of things to ``cLand1st`` I would suggest to adjust LPJG accordingly.

**Comment by nierad** [comment]
Hi Klaus,

I am about to change this in the optimESM branch some time today. For now, please use

file_cLand_1st_monthly "cLand1st_monthly.out"

in the ins-file.
Sorry for the delay, I have to discuss some other issues with Paul first and will let you know asap!

Lars
________________________________
Von: klauswyser ***@***.***>
Gesendet: Donnerstag, 8. Februar 2024 08:52
An: EC-Earth/ece2cmor3 ***@***.***>
Cc: Lars Nieradzik ***@***.***>; Assign ***@***.***>
Betreff: Re: [EC-Earth/ece2cmor3] lpjg cmorisation for OptimESM fails (Issue #798)


LPJG doesn't work any longer because cLand_1st has been changed to cLand1st in ctrl/output-control-files/optimesm/lpjg_cmip6_output.ins:

This may be OK for the filename "cLand1st_monthly.out" but the variable file_cLand1st_monthly is unknown to LPJG. One solution (but not tested) could be

file_cLand_1st_monthly "cLand1st_monthly.out"


but that would break the conventions on how files and variables should be named.

To further increase confusion, both ecearth.ins and global.ins still contain

file_cLand_1st_monthly "cLand_1st_monthly.out"


I guess this requires a more in-depth clean-up on the LPJG guess side. Since @treerink<https://github.com/treerink> already has changed the ece2cmor3 side of things to cLand1st I would suggest to adjust LPJG accordingly.

**Comment by etiennesky** [comment]
Hi @treerink today @nierad told me you want to move the merging of fgco2 into fco2nat, can you explain a bit your reasoning? I don't see why we need a postprocessor for this which makes things a bit complicated.

For my point of view, it works correctly (except for the error in sign) when done within ece2cmor3.

Also, we need to make sure we save the fco2nat from LPJG only for diagnostics purposes.

thanks!

**Comment by treerink** [comment]
Do I get it correctly that the end result should look like this:
```
Amon fco2nat         # where the final Amon fgco2 fco2nat = Amon fco2nat_lpjg - Omon fgco2_nemo
LPJGmon fco2nat      # monthly fco2nat from LPJG
```

**Comment by etiennesky** [comment]
> Do I get it correctly that the end result should look like this:
> 
> ```
> Amon fco2nat         # where the final Amon fco2nat = Amon fco2nat_lpjg - Omon fgco2_nemo
> LPJGmon fco2nat      # monthly fco2nat from LPJG
> ```
> 
> (and no `Lmon fco2nat`)

yes this is perfect! And if it could be done inside ece2cmor3 directly, this is ideal since we would not need to run any postrocessor.

**Comment by nierad** [comment]
> yes this is perfect! And if it could be done inside ece2cmor3 directly, this is ideal since we would not need to run any postprocessor.
That would be branch [789-import-fgco2-in-LPJG](https://github.com/EC-Earth/ece2cmor3/tree/789-import-fgco2-in-LPJG) which is working fine as far as I am concerned. @treerink: Please, let me know, if you want this one, I'd tidy up the code before you merge it.

**Comment by etiennesky** [comment]
> > yes this is perfect! And if it could be done inside ece2cmor3 directly, this is ideal since we would not need to run any postprocessor.
> 
> That would be branch [789-import-fgco2-in-LPJG](https://github.com/EC-Earth/ece2cmor3/tree/789-import-fgco2-in-LPJG) which is working fine as far as I am concerned. @treerink: Please, let me know, if you want this one, I'd tidy up the code before you merge it.

Thanks @nierad are you sure the removal in "invertlat" from the cdo command in commit 1a1a7f604ea256fd703bd83ea14ce53c29ee6150 is required ? This was needed for sure at least with version 1.8.1 of ece2cmors3.  Could you please make available a copy of the nemo output file and the resulting fco2nat you produce using your branch?

**Comment by nierad** [comment]
@etiennesky: Yes, it wouldn't work the other way round. @klauswyser did the simulations and cmorisation, so he can probably provide the data.

**Comment by klauswyser** [comment]
When trying to process daily ``ltran`` (in table LPJGday) I get

````
INFO:ece2cmor3.lpjg2cmor: Processing file /home/sm_wyser/optimesm/sm_wyser/ece-run/CD07/output/lpjg/001/tran_daily.out
INFO:ece2cmor3.lpjg2cmor: Creating lpjg netcdf file for variable tran for year 2000
/home/sm_wyser/cmorize/ece2cmor3/ece2cmor3/lpjg2cmor.py:497: RuntimeWarning: overflow encountered in cast
  variable[:] = np.where(dumvar < 1.e+20, dumvar, 0.)   # TODO: see out2nc for what to do here if you have the LPJG regular grid
Error in calling operator remapycon with:
>>> cdo -O -s -remapycon,n128 -setgrid,/home/sm_wyser/cmorize/ece2cmor3/ece2cmor3/resources/lpjg-grid-content/ingrid_T255_unstructured.txt /scratch/local/LPJGtemp.nc /scratch/local/tran_day_2000.nc<<<
STDOUT:cdf_put_vara_double: name=tran  type=NC_FLOAT  minval=-inf  maxval=0.001188


STDERR:cdo    remapcon (Warning): Using a non-thread-safe NetCDF4/HDF5 library in a multi-threaded environment may lead to erroneous results!
cdo    remapcon (Warning): Use a thread-safe NetCDF4/HDF5 library or the CDO option -L to avoid such errors.
Warning (cdfCheckVarname): Changed double entry of variable name 'lat' to 'lat_2'!
Warning (cdfCheckVarname): Changed double entry of variable name 'lon' to 'lon_2'!
Error (cdf_put_vara_double): NetCDF: Numeric conversion not representable
````

**Comment by klauswyser** [comment]
Output from 1 year of an emission-driven simulation is available from
````
wget -nH -r -e robots=off http://exporter.nsc.liu.se/6b11a0614c894e0dbe65fc207295d4c2/output/{nemo,lpjg,co2box}
````
See [\#1312 on dev portal](https://dev.ec-earth.org/issues/1312#note-95)

**Comment by nierad** [comment]
Thanks, Klaus. I'll look into it.
________________________________
Von: klauswyser ***@***.***>
Gesendet: Freitag, 9. Februar 2024 16:19
An: EC-Earth/ece2cmor3 ***@***.***>
Cc: Lars Nieradzik ***@***.***>; Mention ***@***.***>
Betreff: Re: [EC-Earth/ece2cmor3] lpjg cmorisation for OptimESM fails (Issue #798)


Output from 1 year of an emission-driven simulation is available from

wget -nH -r -e robots=off http://exporter.nsc.liu.se/6b11a0614c894e0dbe65fc207295d4c2/output/{nemo,lpjg,co2box}


See #1312 on dev portal<https://dev.ec-earth.org/issues/1312#note-95>

**Comment by nierad** [comment]
@klauswyser : Which branch did you use?

**Comment by treerink** [comment]
The `ltran` issue should be just investigated from the master I guess?

**Comment by klauswyser** [comment]
> @klauswyser : Which branch did you use?

master (that's why I still have problems with ``fco2nat``)

**Comment by treerink** [comment]
8056eac has added `LPJGmon fco2nat` and the resulting updated output-controlfiles directory for optimism by running `genecec` has been commited in the ECE optimesm branch.

**Comment by klauswyser** [comment]
There are still problems with ``fco2nat`` and ``tsl``, see https://dev.ec-earth.org/issues/1312#note-100

**Comment by nierad** [comment]
Hi Klaus, 
the fco2nat-issue is solved, but not finalised, yet. I think @treerink is working on it. 
`tsl` is a different story and I will get back to it, once Tetralith is back up and running (i.e. Thu I'm afraid).

**Comment by treerink** [comment]
> Hi @treerink today @nierad told me you want to move the merging of fgco2 into fco2nat, can you explain a bit your reasoning? I don't see why we need a postprocessor for this which makes things a bit complicated.
> 
> For my point of view, it works correctly (except for the error in sign) when done within ece2cmor3.

Sharing my thoughts here concerning the `fco2nat` implementation:

- I wonder how robust the call from the lpjg-component to the nemo files is. It potentially could happen that the ECE NEMO files are not (yet) there. A realistic risk when cmorising on the flow? Anyway, at BSC you are rather experienced with cmorising on the flow. If it goes wrong (for instance due to an IO-lag) you can not fix it afterwards anymore because your ECE output has been removed already.
- This exception (including a partly request from another component) is the first of its kind and breaks the full auto and full cover of _genecec_ in this respect. It needs a manual add of _fgco2_ to the the request, but ok we have added that already in this case for optimesm.
- I do not very much like the relative large part of code contained by the `add_nemo_variable` and `find_nemo_file` routines in the _lpjg2cmor.py_, both me and Lars were quite confused about this part when porting the lPJG component to python3. A lot of code for this one variable
- I think the simple variant is rather straightforward, and is not vulnerable to the fact whether ECE NEMO output is written already at the time of LPJG cmorisation, because it is afterwards (and can be repeated later).
- I myself do not really see a drawback in adding a call to such a tiny post process script like the [post processing step for Ofx sftof](https://github.com/EC-Earth/ece2cmor3/wiki/Recommended-strategies#post-ece2cmor3-production--correction-of-ofx-sftof) as it can be included in the technical validation of the cmorised data. 

However, both options are there and can be used, so both are possible to implement as the work is done.
